### ISSUE TITLE
Exception with some special output

### ISSUE THREAD

**Issue by icy** [mpevnev/nice-curses#2]
I have a simple `watch` program here https://github.com/icy/dusybox/tree/master/src/watch/main.d . This tool executes a shell command provided to them as arguments, and capture the output and print them to a ncurse window.

I notice that some output causes `NCException`. For example, `ps x` is fine, but `ps a` (which has very long output in both directions) always generates an exception. I use the `add[n]str` and I think there would be a way to avoid window overflow. 

Moreover, when `NCException` occurs, the original message (that was expected to be drawn on the window) is included in the exception errors, that makes me impossible to display them. That means, the following code will crash the program

```
try { // draw some string }
catch (NCException exc) {
  scr.clear();
  scr.addstr(0, 0, exc.msg);
}
```

This is because `exc.msg` caused the previous exception, and it would cause another exception in `catch` block.

**Comment by mpevnev** [comment]
Hmm. I suspect that underlying waddwstr returns ERR if the string doesn't fit into the window, the manpages do not mention what sort of errors should result in ERR. I'll test this once I'm home. But if that's the case, `addstr` should probably just silently ignore it and print what it can.
