### ISSUE TITLE
Nice-Curses fails to build

### ISSUE THREAD

**Issue by justinmarma** [mpevnev/nice-curses#5]
CTFE is failing when building with Dub, here is a screen shot of the error:
[http://prntscr.com/l0yy2q](url)

The project is empty, there's no code using nice-curses in my source yet.

**Comment by mpevnev** [comment]
Could you post the error messages directly here? For some reasons, prntscr.com doesn't want to work with any of my browsers.

**Comment by mpevnev** [comment]
Nevermind, probably some image processing wasn't yet done, I can see it now.

**Comment by mpevnev** [comment]
Please verify that the fix is working for you as well - I don't have a Windows machine and had to rely on Wine for debugging and compiling, which makes it at least partially suspect.
