### ISSUE TITLE
unicode support not working

### ISSUE THREAD

**Issue by gizmomogwai** [mpevnev/nice-curses#6]
Hi ... I enjoy you dlang lib a lot. Thanks for that.
But now I hit a problem with unicode support.
Even the example in examples/unicode is not working for me.
i tried in osx and linux. any tips here? what am i doing wrong?

**Comment by gizmomogwai** [comment]
sorry. . was a problem on my locale settings.
https://stackoverflow.com/questions/4606570/os-x-terminal-utf-8-issues
had the fix LC_CTYPE=de_DE.UTF-8 helped in my case.

**Comment by mpevnev** [comment]
I will mention that locale can affect unicode support in the readme, thanks for bringing this up.

**Comment by mpevnev** [comment]
Added a quick [commit](45b37d10480a54901e1cc53b5676ee99d232d3c3)
