### ISSUE TITLE
draw a table?

### ISSUE THREAD

**Issue by biocyberman** [mpevnev/nice-curses#8]
I am new to ncurses, so the current documentation does not help. Could you please show an example to draw the following table which was taken from [here](https://ozh.github.io/ascii-tables/)?

```
+----------------------------------+---------+------------------------+----------------+
|               Col1               |  Col2   |          Col3          | Numeric Column |
+----------------------------------+---------+------------------------+----------------+
| Value 1                          | Value 2 | 123                    |           10.0 |
| Separate                         | cols    | with a tab or 4 spaces |       -2,027.1 |
| This is a row with only one cell |         |                        |                |
+----------------------------------+---------+------------------------+----------------+
```

**Comment by mpevnev** [comment]
If I felt lazy, I'd just defined a helper function to draw a box (a sequence of `vline` and `hline` calls, maybe with an `addch` for corners), use that to draw cells, and plop the strings into them with `addnstr` and\or `addAligned`.

Otherwise, I'd overengineer it horrifically, which is a lot more fun.

**Comment by biocyberman** [comment]
Thanks for the strategy, it still involves quite lot of handcraft. I think not, but does nice-curses support form currently? The C version seems to take quite many lines to draw a simple form. It returns, it offer smooth line drawing in the console.

**Comment by mpevnev** [comment]
No, there are no wrappers for `form.h` API.

> The C version seems to take quite many lines to draw a simple form

`nice-curses` doesn't help with that for the most part, unfortunately. Initialization and shutdown code is reduced a lot, but drawing is more or less the same.

> It returns, it offer smooth line drawing in the console.

Sorry, I don't quite get it.

**Comment by biocyberman** [comment]
> >     It returns, it offer smooth line drawing in the console.
> 
> Sorry, I don't quite get it.
I meant, "in returns, form.h gives smooth line rendering in the console.
Anyway, thanks for clarifications.
